### ISSUE TITLE
Add IPv6 connectivity

### ISSUE THREAD

**Issue by hamiltonp** [Bylon/TOR_Middlebox#1] opened 2017-10-06 03:18 UTC
Tor supports IPv6 connectivity, is there any chance to enable IPv6 within this project?

There are 2 programs that could help with this, wide-dhcpv6-server/client/relay and radvd.

**Comment by Bylon** [comment] 2017-10-07 07:41
Thank you for your interest with the project.

If you don't disable ipv6 as explained in Optional step 6, your guest can use the link-local ipv6
Here is from the guest, I ping the other side of our 'vnet0' host interface:

```
$ ping6 -I eth0 fe80::c3f:daff:fe28:847d
PING fe80::c3f:daff:fe28:847d(fe80::c3f:daff:fe28:847d) from fe80::a00:27ff:fefd:94f2 eth0: 56 data bytes
64 bytes from fe80::c3f:daff:fe28:847d: icmp_seq=1 ttl=64 time=0.409 ms

```

So for now, there is very limited connectivity.

We have several issues to fix from there:
- We might want to allow the guest to automatically get a global ipv6 address. The standard way is that the client auto-configures itself, but indeed forcing an ipv6 address with Wide could work.
- We then want to instruct the host what to do with those ipv6 packets on vnet0. For global ipv6 addresses the default kernel action will probably be to forwarding them, which denies the anonymity of TOR! So we would have to capture the iv6 traffic on vnet0 and route it via TOR.
- And I am assuming here TOR is routing ipv6 "natively"... it might do otherwise, for example tunnelling via ipv4, so the first step is to look into that in fact!

Nice extension... especially if we want to make is as transparent as ipv4 is for now!

**Comment by Bylon** [comment] 2017-10-10 17:48
Some good news and less good news!

I am assuming we are using these scripts from a "standard desktop", as opposed to a Linux box which purpose is being a router! That is because if you are capable of setting up a router, you probably don't need these scripts...

So I suppose the user to this "standard desktop" still wants to use SLAAC, which is an easy way to get your ipv6 stack up an running. Of course you have an internet provider that is ipv6 compatible (otherwise you wouldn't need this ticket) and all is already working with SLAAC.

You also want your VM to work with SLAAC, since the goal is that it is "transparent", and you have nothing at all to set inside the VM for that to work.

Now the bad news...
ipv6 routing works usually (good practice) with link-local addresses as next-hop.
Using radvd with basic configuration correctly advertise the link-local address of our vnet0 to the guest O.S. inside the VM.

Unfortunately there is a bug in TOR, or at least very poor documentation... which anyway general about ipv6!
The issue is that you cannot bind a link-local address. Indeed binding a link-local address means you add a parameter in the system call: the interface.
I tried the "usual way" to do that [fe80::x:y:z:t%vnet0], it is simply ignoring %vnet0 and failing to bind. With vnet0 elsewhere, it fails to parse.

So I'll have to go down to tor's code, and  potentially open a bug ticket or documentation ticket.

**Workaround** I am exploring now is to give our vnet0 some hardcoded global ipv6 and advertise that as the next-hop for our VM.

Doing that "manually" and setting the next-hop inside the VM works... partially.


Second shortcoming of TOR...

Now you are aware there is no such thing as DNS6. Plain old DNS continue to work, they just added AAAA addresses that correspond to the ipv6 of the server.

Unfortunately, when you are plugged to the ipV4 stack (as is the case so far for our scripts) the DNS does NOT get you back the AAAA address.

Fortunately enough, when you use an ipv6 stack, you get both DNS entries: V4 and V6.
So when you would like to use the IPV6 stack, all the DNS requests would have to be torrified to the V6 stack, otherwise you would have "unresolved hosts".

That is stil on the TODO list.


So far, manually tampering with the routes in the VM I have achieved that from inside the VM:

```
$ curl -g -6 'http://[2604:7780:200:305:f816:3eff:fe85:9193]'
2605:e200:d111:1:225:90ff:fe24:3f9e
```

This ipv6 address we ask for it that of ip6.icanhazip.com
But when we try it by name, we get:

```
$ curl -g -6 http://ip6.icanhazip.com
curl: (6) Could not resolve host: ip6.icanhazip.com
```

And that is because I still didn't migrate the DNS stack to IPV6.

Indeed because when you try through socks5 within the host it works as you can see (both dns 4 and 6 and returning data):
```
$ curl -g -6 --socks5 '[::1]:9050' http://ip6.icanhazip.com
2a03:f85:8::7
$ curl --socks5 '[::1]:9050' http://www.icanhazip.com
192.36.27.7
```

Last shortcoming of tor...

There is absolutely no way to force selection of exit nodes so that you are sure they have ipv6 on!
Obviously, should you use an non-ipv6 exit node, all that will fail since you won't have "connectivity".

So far I didn't have the case that there is no ipv6 connectivity, and there might be an "auto configuration" of tor so that if forces the use of ipv6 exit nodes when you do ipv6.

... another thing to check with the tor mailing list!

Nevertheless, since potentially not all the exit nodes have ipv6 on, using ipv6 (assuming tor auto-magically assigns you a workable exit) will augment the risks because an adversary needs fewer exit nodes to try to unscramble things.

**Comment by Bylon** [comment] 2017-10-15 15:01
Good news, I have successfully patch tor so that we can serve ipv6 addresses on link-local addresses.

Bad news is that your request gave me the idea to re-factor completely how middlebox works.

In fact the new idea is to generate automatically all the configurations from default variable, and install it once. A bit like you would do with grub.
This would avoid having to play with multiple configuration files, with the risk of error.

Second bad news is that it might take some time for the Tor team to accept my patch (if ever!) or provide another working alternative. They might also deem unnecessary to provide a backport to 0.2.9.11 which is used with Ubuntu 16.04, or the even more antiquate version in 14.04.
So even if the patch is accepted, or the enhancement included in another way, it will take some time to be in an Ubuntu future version.

So I'll provide the source patch of tor for Ubuntu 16.04, plus a compiled version for x64 in case you trust me and don't want to compile yourself!
For other Linuxes you'll have to compile after having applied the patch.

**Comment by hamiltonp** [comment] 2017-12-26 19:27
I personally don't like to virtualize an OS just for using it through Tor connection, I prefer to make a chroot or a LXC container, do the Xorg tricks to run graphical apps inside and run with ip-netns with iptables rules for Tor transparent proxying. The main advantage is that a VM can isolate the hardware and hide their infos (such as WebRTC Hardware IDs), but a Firefox with WebRTC disabled, a fake/temporary /home/* and User Agent spoofing can do the same if I had to run inside QEMU or VirtualBox.

I perceived  2 problems with Tor when using a veth or bridge:

**1 - When using Tor DNS service, everything runs ok, but after some time (minutes), the DNS AAAA lookup through [::1]:53 just stop working, and also if you put down the Internet cable and reconnect, you'll have to restart the Tor service with $/etc/init.d/tor restart to make the [::1]:53 work again. But the 127.0.0.1:53 continues to work.**

This is my config for Tor DNS:

DNSPort 127.0.0.1:53 IPv6Traffic PreferIPv6
DNSPort [::1]:53 IPv6Traffic
AutomapHostsOnResolve 1
ClientUseIPv6 1
ClientUseIPv4 1

Replacing the local loopback address with one of a veth or bridge (usually [fd00::1]:53 with a peer interface with fd00::2/64 pointing to the gateway fd00::1/64) and connecting a ip-netns container in a peer interface of it produces the same behavior.

**2 - Any try to setup an ip-netns namespace with TransPort and DNSPort pointing to a non-loopback address using IPv6 fails (would be the same with a bridge+container or bridge+vm:**

ip netns add ns1
ip link add vnet1 type veth peer name vnet2
ip link set vnet2 netns ns1

ip addr add 10.0.0.1/24 dev vnet1
ip -6 addr add fd00::1/64 dev vnet1
ip link set vnet1 up
ip netns exec NETNS ip addr add 10.0.0.2/24 dev vnet2
ip -6 netns exec NETNS ip -6 addr add fd00::2/64 dev vnet2
ip netns exec NETNS ip link set vnet2 up
ip netns exec NETNS ip route add default via 10.0.0.1 dev vnet2
ip -6 netns exec NETNS ip -6 route add default via fd00::1 dev vnet2

iptables -t nat -A POSTROUTING -s 10.0.0.0/24 -o vnet1 -j MASQUERADE
ip6tables -t nat -A POSTROUTING -s fd00::/64 -o vnet1 -j MASQUERADE
iptables -t nat -A  PREROUTING -i OUTSIDE -p udp -d 10.0.0.1 --dport 53 -j DNAT --to-destination 10.0.0.1:9153
ip6tables -t nat -A  PREROUTING -i OUTSIDE -p udp -d fd00::1 --dport 53 -j DNAT --to-destination fd00::1:9153
iptables -t nat -A  PREROUTING -i OUTSIDE -p tcp --syn -j DNAT --to-destination 10.0.0.1:9040
ip6tables -t nat -A  PREROUTING -i OUTSIDE -p tcp --syn -j DNAT --to-destination fd00::1:9040
iptables -t nat -A  PREROUTING -i OUTSIDE -p tcp --syn -j DNAT --to-destination 10.0.0.1:9040
ip6tables -t nat -A  PREROUTING -i OUTSIDE -p tcp --syn -j DNAT --to-destination fd00::1:9040
iptables -A OUTPUT -m state -o OUTSIDE --state ESTABLISHED,RELATED -j ACCEPT
ip6tables -A OUTPUT -m state -o OUTSIDE --state ESTABLISHED,RELATED -j ACCEPT
iptables -I INPUT -i OUTSIDE -p udp --destination 10.0.0.1 --dport 9153 -j ACCEPT
ip6tables -I INPUT -i OUTSIDE -p udp --destination fd00::1 --dport 9153 -j ACCEPT
iptables -I INPUT -i OUTSIDE -p tcp --destination 10.0.0.1 --dport 9040 -j ACCEPT
ip6tables -I INPUT -i OUTSIDE -p tcp --destination fd00::1 --dport 9040 -j ACCEPT
iptables -A INPUT -i OUTSIDE -j DROP
ip6tables -A INPUT -i OUTSIDE -j DROP

mkdir -pv /etc/netns
mkdir -pv /etc/netns/ns1
echo "nameserver 10.0.0.1" >> /etc/netns/ns1/resolv.conf
echo "nameserver fd00::1" >> /etc/netns/ns1/resolv.conf
sysctl -q -w net.ipv4.ip_nonlocal_bind=1
sysctl -q -w net.ipv6.ip_nonlocal_bind=1

ip netns exec ns1 bash

===

Tor config:

AutomapHostsOnResolve 1
VirtualAddrNetworkIPv4 10.0.0.2/16
TransPort 10.0.0.1:9040 IPv6Traffic
DNSPort 10.0.0.1:5354 IPv6Traffic
ClientUseIPv4 1
VirtualAddrNetworkIPv6 [fe80::]/10
TransPort [fd00::1]:9040 IPv6Traffic PreferIPv6
DNSPort [fd00::1]:5354 IPv6Traffic PreferIPv6
ClientUseIPv6 1
SOCKSPort 0

The scheme above setups a network namespace with IP4 and 6 adresses, the IPv4 adresses works 100%, but the 6 ones don't. Trying to run $w3m with a IPv6 only site, it gives:

_root@unknown:/home/nobody# w3m -6 v6.testmyipv6.com
w3m: Can't load v6.testmyipv6.com._

Looking at $ tcpdump -vv -i vnet1

_tcpdump: listening on in-torjail, link-type EN10MB (Ethernet), capture size 262144 bytes
14:01:19.325265 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 32) fd00::2 > ff02::1:ff00:1: [icmp6 sum ok] ICMP6, neighbor solicitation, length 32, who has fd00::1
	  source link-address option (1), length 8 (1): 0e:d9:13:5c:c5:4e
	    0x0000:  0ed9 135c c54e
14:01:19.325292 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 32) fd00::1 > fd00::2: [icmp6 sum ok] ICMP6, neighbor advertisement, length 32, tgt is fd00::1, Flags [router, solicited, override]
	  destination link-address option (2), length 8 (1): a6:4a:22:b8:bc:0e
	    0x0000:  a64a 22b8 bc0e
14:01:19.325297 IP6 (flowlabel 0x01839, hlim 64, next-header UDP (17) payload length: 43) fd00::2.36537 > fd00::1.domain: [bad udp cksum 0xfa40 -> 0xfdc7!] 31377+ AAAA? v6.testmyipv6.com. (35)
14:01:19.325311 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 128) fe80::a44a:22ff:feb8:bc0e > fd00::2: [icmp6 sum ok] ICMP6, redirect, length 128, fd00::1:5354 to fd00::1:5354
	  redirected header option (4), length 88 (11): 
	    0x0000:  040b 0000 0000 0000 6000 1839 002b 1140
	    0x0010:  fd00 0000 0000 0000 0000 0000 0000 0002
	    0x0020:  fd00 0000 0000 0000 0000 0000 0001 5354
	    0x0030:  8eb9 0035 002b 4d95 7a91 0100 0001 0000
	    0x0040:  0000 0000 0276 360a 7465 7374 6d79 6970
	    0x0050:  7636 0363 6f6d 0000
	    0x0000:  0000 0000 0000 6000 1839 002b 1140 fd00
	    0x0010:  0000 0000 0000 0000 0000 0000 0002 fd00
	    0x0020:  0000 0000 0000 0000 0000 0001 5354 8eb9
	    0x0030:  0035 002b 4d95 7a91 0100 0001 0000 0000
	    0x0040:  0000 0276 360a 7465 7374 6d79 6970 7636
	    0x0050:  0363 6f6d 0000
14:01:19.325317 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 32) fe80::a44a:22ff:feb8:bc0e > ff02::1:ff01:5354: [icmp6 sum ok] ICMP6, neighbor solicitation, length 32, who has fd00::1:5354
	  source link-address option (1), length 8 (1): a6:4a:22:b8:bc:0e
	    0x0000:  a64a 22b8 bc0e
14:01:20.326182 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 32) fe80::a44a:22ff:feb8:bc0e > ff02::1:ff01:5354: [icmp6 sum ok] ICMP6, neighbor solicitation, length 32, who has fd00::1:5354
	  source link-address option (1), length 8 (1): a6:4a:22:b8:bc:0e
	    0x0000:  a64a 22b8 bc0e
14:01:21.350458 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 32) fe80::a44a:22ff:feb8:bc0e > ff02::1:ff01:5354: [icmp6 sum ok] ICMP6, neighbor solicitation, length 32, who has fd00::1:5354
	  source link-address option (1), length 8 (1): a6:4a:22:b8:bc:0e
	    0x0000:  a64a 22b8 bc0e
14:01:22.374287 IP6 (flowlabel 0xf728c, hlim 64, next-header ICMPv6 (58) payload length: 91) fd00::1 > fd00::2: [icmp6 sum ok] ICMP6, destination unreachable, unreachable address fd00::1
14:01:24.330523 IP6 (flowlabel 0x01839, hlim 64, next-header UDP (17) payload length: 43) fd00::2.36537 > fd00::1.domain: [bad udp cksum 0xfa40 -> 0xfdc7!] 31377+ AAAA? v6.testmyipv6.com. (35)
14:01:24.330570 IP6 (hlim 255, next-header ICMPv6 (58) payload length: 128) fe80::a44a:22ff:feb8:bc0e > fd00::2: [icmp6 sum ok] ICMP6, redirect, length 128, fd00::1:5354 to fd00::1:5354
	  redirected header option (4), length 88 (11): 
	    0x0000:  040b 0000 0000 0000 6000 1839 002b 1140
	    0x0010:  fd00 0000 0000 0000 0000 0000 0000 0002
	    0x0020:  fd00 0000 0000 0000 0000 0000 0001 5354
	    0x0030:  8eb9 0035 002b 4d95 7a91 0100 0001 0000
	    0x0040:  0000 0000 0276 360a 7465 7374 6d79 6970
	    0x0050:  7636 0363 6f6d 0000
	    0x0000:  0000 0000 0000 6000 1839 002b 1140 fd00
	    0x0010:  0000 0000 0000 0000 0000 0000 0002 fd00
	    0x0020:  0000 0000 0000 0000 0000 0001 5354 8eb9
	    0x0030:  0035 002b 4d95 7a91 0100 0001 0000 0000
	    0x0040:  0000 0276 360a 7465 7374 6d79 6970 7636
	    0x0050:  0363 6f6d 0000
(and so on...)_

$(ip -6 neigh show) and $(ip -6 route show) shows everything is ok with the IPv6 setup of the internal gateway. Wireshark says "Destination unreachable" on [fd00::1]:

In few words: vnet2 peer interface don't see any [fd00::1]:9153

**Comment by Bylon** [comment] 2017-12-27 17:43
I am not yet familiar with ip-netns. As libBletchley suggested (see the other issues) I tried firejail, and adopted it. I made a wiki page on that, and when I want to use only firefox, I do it now through firejail which is indeed must faster than a full VM.

I am assuming that you might achieve the same level of isolation with LXC + netns that you get through firejail, looking at the description of LXC.

Userspace isolation is apparently fashionable, there are quite a lot of alternatives and things are moving. I'll get a try with LXC (when I'll have time).

Currently I am rewriting the logic of tor middlebox to make it more "automatic".  Instead of reading scattered information from various config files you have to manually edit, the configuration will be in one place and the middlebox script will apply changes to the relevant system configuration files (saving them in the process).

**About your 1:**
When you have both ipv4 and ipv6 connectivity, I don't intend to set up DNS over ipv6 since you don't need it! Indeed plain old DNS on ipv4 is perfectly capable of fetching AAAA.
There are also no O.S. nor application that I know of that would be ipv6 enable and not able to do ipv4... and obviously you have plenty of example of the opposite!

So ipv6 DNS would be in the case you have no ipv4 at all (or you disabled it in the configuration).

In any case, you don't really need 2 different DNS!


**About your 2:**
It looks related to netns. It works fine with firejail (also using network isolation) although I must admit I am not at the point where I configured ipv6 for firejail.


**General comment**
ipv6 is still an "unfinished business" for Tor. So having things that work for ipv4 and don't for ipv6 does not surprise me!

See, I had to patch Tor (I now have a nice PPA with the package ready!) to be able to bind link-local ipv6 address. It is not considered as a "bug" but as "enhancement"!

Surely that if you couldn't bind on 192.168.0.N and needed a global ipv4 address to bind, that would be considered as a "bug"... well, not on ipv6!

There is also no reliable way to know whether the circuit your client build will have full ipv6 connectivity, since a fair percentage of relays are still ipv4 only. Apparently all the ipv6xxxx token in the tor configuration are merely "hints" so far that you would prefer ipv6.

**Comment by Bylon** [comment] 2017-12-27 18:15
Would you have more information about the privacy leak you refer to with

> hardware and hide their infos (such as WebRTC Hardware IDs)

Indeed there is a method to get devices, assuming audio/video capable devices... same as there always was a method to guess the screen resolution. Each of these detections is a hint to pinpoint you, but this "enumeratedevice" method could be called by any script, not only WebRTC. There is a file though in the profile that seems to keep enumerated devices (enumerate_devices.txt), it looks not worse than a cookie file.

So to avoid a call to: [navigator.mediaDevices.enumerateDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices), even outside of WebRTC related things, wouldn't you have to completely disable scripts?

I am using uMatrix, very good addon that mainly can do first party isolation, but also block scripts, referrer, switch user agents, etc...

**Comment by Bylon** [comment] 2018-01-12 23:19
There are strange things on your configuration:

- you redirect DNS to port 9153 (iptables) but your torrc says that tor listens DNS on 5354
- note sure you have an ipv6 route to your fd00::/10. Look at route -6 -n to see if it is there

The script has now been updated and works with firejail that provides similar features to what you use as a sandbox.

If you want to see how the script does, you can do a dry run (option -s).

For example:
```
mkdir /tmp/mbx
./middlebox -s /tmp/mbx -v
```

Nothing will be changed on your configuration, it will use default values that are in the script and output all the files it would have created under /tmp/mbx.

You can then look at those files and adapt to your own sandbox.

Again, you don't need both ipv4 and ipv6 dns, your sandbox will use only one of them, and unfortunately it is probably the one with ipv4 that is much less reliable to retrieve AAAA records.
If you manage to make you sandbox to use DNS6 instead, you'll be lucky and have better name resolution for ipv6.

Although the state of ipv6 is not perfect (see the README.md), I am closing this ticket.
I did what I could with the current state of progress of ipv6 implementation in tor and firejail. Let's hope more ipv6 compliance will be there in the future!

**Closed by Bylon** 2018-01-12 23:19 UTC
