### ISSUE TITLE
DNS resolution blocked (should ttdnsd become a part of the middlebox?)

### ISSUE THREAD

**Issue by libBletchley** [Bylon/TOR_Middlebox#4] opened 2017-11-28 15:49 UTC
When using _firejail_ to sandbox a _wget_ session over the TOR middlebox, the DNS resolution fails when the host is not something I've recently accessed (and thus the IP is not cached):
```
# firejail --noprofile --net=vnet0 wget 'https://raw.githubusercontent.com/netblue30/firejail/master/etc/fetchmail.profile'
Parent pid 31690, child pid 31691
The new log directory is /proc/31691/root/var/log

Interface        MAC                IP               Mask             Status
lo                                  127.0.0.1        255.0.0.0        UP
eth0             xx:xx:xx:xx:xx:xx  172.16.0.244     255.255.255.0    UP
Default gateway 172.16.0.1

Child process initialized
--2017-11-28 16:29:06--  https://raw.githubusercontent.com/netblue30/firejail/master/etc/fetchmail.profile
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Name or service not known.
wget: unable to resolve host address ‘raw.githubusercontent.com’

Parent is shutting down, bye...
```
So it seems the TOR middlebox is somehow botching the DNS lookup.  Tor does not handle UDP packets, so I'm a bit fuzzy on how dnsmasq is being used to do non-leaky DNS UDP lookups.  I also wonder why `ttdnsd` is not in play, which involves a local DNS server that caches lookups and also forces lookups to happen over tor (Tails uses it iirc).

I have a slight suspicion that it's similar to this bug: https://github.com/netblue30/firejail/issues/1591.  But in that case it can be addressed by firejail.  In the case of forcing a firejail over tor, there can be no expectation that the sandboxed app be aware of `tor-resolve`.  Is this something that can be solved in the middlebox?

**Comment by Bylon** [comment] 2017-11-29 19:43
Hi, I tested firejail after your ticket #3 and noticed the issue.

The issue does not seem to be around how the Middlebox iptables rules handle DNS but about firejail not receiving a valide DNS. There are some posts about that, the one you mention and others, but no clear solution.

You can notice that if you manually add the dns on the firejail command (mine is 192.168.0.254 since it is served by my ISP box) it works fine. I have not checked yet that DNS do not leak but assuming so.

So in my case, doing
`firejail --net=vnet0 --dns=192.168.0.254 wget 'http://whatismyip.akamai.com'`

... fixes the issue and works perfectly.

Although I have noticed that if I run the command repetitively, I get a new Tor identity each time... which is also something I can't explain right now.


Since firejail seems a nice trick indeed, I'll do some further investigation about that.

**Comment by Bylon** [comment] 2017-11-30 18:10
Follow up:
- with 192.168.0.254 as DNS it was working, but since in my own setting I have 192.168.0.0/24 as NON-Tor, it was indeed leeking DNS... as intended if you use a specified NON-Tor address you specify.
- since we are diverting the DNS through Tor, any reasonably valid ip address works for DNS since we are not really using that address (it also proves the non-leaking). So choose an neutral address you would not care to disclose things in case you think it might leak.
```

$ firejail --net=vnet0 --dns=212.77.1.243
Interface        MAC                IP               Mask             Status
lo                                  127.0.0.1        255.0.0.0        UP    
eth0             7e:c4:81:50:da:c7  172.16.0.254     255.255.255.0    UP    
Default gateway 172.16.0.1
DNS server 212.77.1.243

Child process initialized
$ curl 'http://whatismyip.akamai.com'
192.42.116.16
```

212.77.1.243 is www.vatican.va
It is not a DNS but the ip of the website itself, and it works perfectly with our middlebox since is it not really used as a DNS!

Still investigating this non-DNS issue, don't hesitate to comment if you find a clue.

**Comment by libBletchley** [comment] 2017-11-30 21:44
It would be ideal to have a local DNS server that uses Tor, which could then be used as the DNS server for all lookups (even if the client is not using tor).  It would also reduce the number of lookups.  But the https://github.com/pparent76/ttdnsd project seems dead.  It references Debian 5.0 (and i recall debian dropping it around that time).  It has a dead URL to torproject.org, and it's broken in Tails:

https://tails.boum.org/contribute/design/Tor_enforcement/DNS/ttdnsd_broken/

I think i saw that it's still in Tails.. just sitting idly.

I don't understand why the vatican IP works.  Is the middlebox intercepting DNS requests and rerouting them?

BTW, you're using akamai.com to get your IP, but I'm opting to use CloudFlared sites for this so that the workload is carried by the most harmful company that impedes Tor user liberties.
```
firejail --net=vnet0 --dns=198.41.215.162 lynx -dump -nolist 'http://change.org' | grep -i ray.id
```

**Comment by Bylon** [comment] 2017-11-30 23:35
So here is why.

The problem seems to be the way firejail guesses the dns when nothing is specified.

Since we have NetworkManager that uses dnsmasq, the latter is serving dns on all interfaces and in 127.0.1.1 which is the one the system will use by default.

We can prove that using the nice tcpdump trick on this post:
https://askubuntu.com/questions/637893/how-to-know-what-dns-am-i-using-in-ubuntu-from-14-04-onwards/637894#637894

Then, starting firejail with no dns arguments makes it listen to the "default dns" as seen by tcpdump, which is 127.0.1.1
This can be proven again with the same tcpdump. We just need to start firejail with --noprofile so that we can use sudo and tcpdump!

Obviously, inside our jail, nobody listens UDP 53 on localhost, so a dig will fail with "no server could be reached" after a timeout on UDP to 127.0.1.1:53


On the other hand, when we look at what VirtualBox does, it assigns the same ip for gateway and dns. In our default middlebox configuration, this is 172.16.0.1.

So to mimic VirtualBox, instead of using an IP like the one of the Vatican (or any other IP) the best is simply to use the our local network vnet0 we created on purpose.


So, due to the combination of NetworkManager + dnsmasq and how firejail guesses the DNS, we don't have DNS resolution if we don't force the DNS. This is independant of middlebox.

If we don't use middlebox, we must force a valid DNS for firejail

Since we use middlebox, a trick that will always work is using the vnet0 address on our host: 172.16.0.1 (in the default configuration)

So, basically, we can use:
`$ firejail --net=vnet0 --dns=$( ifconfig vnet0 | sed -n '/inet adr/{s/.*inet adr://;s/ .*//p}' )`


And to answer to your questions:
- dns lookups should already be cached by dnsmasq/NetworkManager
- yes middlebox's iptables rules divert DNS to tor, as long as the DNS request arrives on vnet0. Look at the iptables rules: UDP 53 is redirected to UDP 60 on 172.16.0.1 which happens to be listened by Tor for DNS. Then there is another rule to allow Tor to reply to the DNS. Since is it a redirect rule, the traffic is redirected to the host, whatever the destination it originally had. This is why any valid address that will cause UDP:53 packets to arrive on vnet0 will work. We simply choose 172.16.0.1 here, which we always know to be valid since it is the vnet0 IP address on the side of the host.


Since it is "work as design" by combination of what we have installed on Debian/Ubuntu, I am considering closing this ticket with the above workaround.

A proper closing would anyway to do file a "bug report/enhancement request" on firejail upstream. Not sure though we can propose a "more clever" algorithm to guess the right DNS!

**Comment by libBletchley** [comment] 2017-12-01 14:06
@Bylon 

Thank you!  Excellent work.  I hope your finding also helps others - it has certainly helped me.

I should point out that `ifconfig` is a tool for root, while firejail will be mostly used with user privileges.  And also my Debian version of `ifconfig` output differs from your Ubuntu version enough that the sed code shoots blanks.  So I would replace the _--dns=_ with this version:
```
firejail --net=vnet0 --dns="$(ip address show dev vnet0 | awk '/inet\>/{gsub(/[/].*/,""); print $2 }')" lynx -dump -nolist 'http://zoodreams.ru' | grep -i ray.id
```
I also have a decent way to test this.  These lists are of hosts likely to produce CloudFlare CAPTCHAs:
 * `sorted_unique_cf.txt` file from [this project](https://github.com/pirate/sites-using-cloudflare)
 * `cloudflare-list.txt` from [this project](https://github.com/themusicgod1/cloudflare-tor)
Selecting a domain at random from those lists is a way to get a domain name that's not recently been resolved locally.  So if _--dns=_  is omitted, then then DNS resolution fails.  If supplied, DNS resolution works.  Then if omitted again, it works because the previous session cached it.

**Comment by Bylon** [comment] 2017-12-01 20:27
To prove non-leakage you can use several clues.

First you can look at the iptables rules we use for our middlebox, here are some relevant to dns:

```
$ sudo iptables -L -v -n --line-numbers; sudo iptables -L -v -n --line-numbers -t nat
Chain INPUT (policy ACCEPT 1630K packets, 7318M bytes)
num   pkts bytes target     prot opt in     out     source               destination         
(...)
8        0     0 ACCEPT     udp  --  vnet0  *       172.16.0.0/24        172.16.0.1           udp dpt:5353

Chain OUTPUT (policy ACCEPT 931K packets, 5539M bytes)
num   pkts bytes target     prot opt in     out     source               destination         
(...)
8        0     0 ACCEPT     udp  --  *      vnet0   172.16.0.1           172.16.0.0/24        udp spt:5353

Chain PREROUTING (policy ACCEPT 33 packets, 5317 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
(...)
3        0     0 REDIRECT   udp  --  vnet0  *       172.16.0.0/24        0.0.0.0/0            udp dpt:53 redir ports 5353

```

That is when the machine starts and nothing has been done with our middlebox.

Let's do something and look again:

```
$ firejail --net=vnet0 --dns=172.16.0.1 wget -q http://whatismyip.akamai.com -O - && sudo iptables -L -v -n --line-numbers; sudo iptables -L -v -n --line-numbers -t nat
Reading profile /etc/firejail/generic.profile
(...)
Interface        MAC                IP               Mask             Status
lo                                  127.0.0.1        255.0.0.0        UP    
eth0             3e:7b:66:a5:5e:e1  172.16.0.94      255.255.255.0    UP    
Default gateway 172.16.0.1
DNS server 172.16.0.1

Child process initialized
51.15.53.83
parent is shutting down, bye...

Chain INPUT (policy ACCEPT 3872K packets, 16G bytes)
num   pkts bytes target     prot opt in     out     source               destination         
(...)
8        2   134 ACCEPT     udp  --  vnet0  *       172.16.0.0/24        172.16.0.1           udp dpt:5353

Chain OUTPUT (policy ACCEPT 2136K packets, 14G bytes)
num   pkts bytes target     prot opt in     out     source               destination         
(...)
8        2   150 ACCEPT     udp  --  *      vnet0   172.16.0.1           172.16.0.0/24        udp spt:5353

Chain PREROUTING (policy ACCEPT 35 packets, 5528 bytes)
num   pkts bytes target     prot opt in     out     source               destination         
3        1    67 REDIRECT   udp  --  vnet0  *       172.16.0.0/24        0.0.0.0/0            udp dpt:53 redir ports 5353
```

So you see right now that we have
- redirected 1 request from 172.16.0.0/24 (our random firejail address being 172.16.0.94 this time) from port 53 to 5353 (I use that on my config)
- this packet represented 2 UDP packets that where authorized in and out.
- this correspond to the firejail we used that did an dns lookup on whatismyip.akamai.com

This is only a clue that DNS went through tor.
You can of course add log rules on UDP 53 on vnet0 to check that.
In parallel of doing something in firejail/VM you can run tcdump or wireshark to check that no DNS lookup related to you cloaked activity is leaked.

I don't know about Chromium leaking DNS, but Firefox has a protection about that. You have to especially toggle a config value to be able to reach onion sites. That prevents you from accidentally leaking onion lookups. This is in the wiki.


About this ticket, I'll keep it open a little bit longer. When I'll have time I'll see if it is worth filing a ticket on firejail's github to mitigate this issue.

**Comment by Bylon** [comment] 2017-12-10 08:58
Ticket opened (Enhancement Request - since the workaround is trivial) at firejail.

https://github.com/netblue30/firejail/issues/1672

**Closed by Bylon** 2017-12-10 08:58 UTC
